### ISSUE TITLE
`kubectl argo rollouts dashboard` always spins up an empty dashboard with namespace set to `unknown`

### ISSUE THREAD

**Issue by spkane** [argoproj/argo-rollouts#1547]
## Summary 

If I have run the following:

```sh
$ kubectl config set-context --current --namespace=default
Context "kind-kind" modified.

$ kubectl -n default get rollouts
NAME          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE
canary-demo   5         5         5            5

$ kubectl argo rollouts dashboard -n default
```

I would expect the dashboard to be setup properly and show a UI representation of what I can see using:

```sh
$ kubectl argo rollouts get rollout canary-demo --watch
```

## Diagnostics

What version of Argo Rollouts are you running?

* `quay.io/argoproj/argo-rollouts:v1.0.6`

```
$ kubectl argo rollouts version
kubectl-argo-rollouts: v1.0.4+c63b6c1
  BuildDate: 2021-08-03T02:45:19Z
  GitCommit: c63b6c1f5134a9f19caae37765f1a8a145f62d7d
  GitTreeState: clean
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
```

![image](https://user-images.githubusercontent.com/129629/134989158-4ec294c4-4fb9-4c70-8a8b-1fee9ac29d32.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by spkane** [comment]
The new plugin actually seems worse. I can use something like this fine:

```sh
$ kubectl argo rollouts get rollout canary-demo --watch
```

but when I try to bring up the dashboard with:

```sh
$ kubectl argo rollouts dashboard -n default

INFO[0000] Argo Rollouts Dashboard is now available at localhost 3100
```

then I open up: 

[http://127.0.0.1:3100/](http://127.0.0.1:3100/)

I get nothing but a blank screen.

Viewing page source reveals this:

```html
<!doctype html><html lang="en"><head><base href="/"/><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Argo Rollouts</title></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script src="main.083109c2fe576967532d.js"></script></body></html>
```

The new version of the kubectl plugin is:

```sh
$ kubectl argo rollouts version

kubectl-argo-rollouts: v1.1.0-rc1+c1353e4
  BuildDate: 2021-09-21T19:55:57Z
  GitCommit: c1353e4a44acc3df8f7af2ad0d7d3325e689f5d0
  GitTreeState: clean
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
```

**Comment by jessesuen** [comment]
I'm unable to reproduce this. I've tested with the same version using safari, chrome, and brave:

```
kubectl-argo-rollouts: v1.1.0-rc1+c1353e4
  BuildDate: 2021-09-21T19:55:57Z
  GitCommit: c1353e4a44acc3df8f7af2ad0d7d3325e689f5d0
  GitTreeState: clean
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
```

The fact that you have the source returned is a good thing. I wonder if you have something in your browser preventing UI from rendering (e.g. javascript disable). Perhaps opening your browser's developer tools may give some clues.

**Comment by sof2000** [comment]
Fixed this issue by using image v1.1.1 from https://quay.io/repository/argoproj/kubectl-argo-rollouts?tag=latest&tab=tags

**Comment by AntSworD** [comment]
Emm..
Looks like the same problem occured again, already try latest/v1.3.0-rc2..etc
![image](https://user-images.githubusercontent.com/2549087/188921869-e9b1d368-904e-4b2a-8ec8-f9917843c3c4.png)

**Comment by Armstrong4444** [comment]
I probably use a workaround. I downloaded install-dashboard.yaml (https://github.com/argoproj/argo-rollouts/blob/master/manifests/dashboard-install.yaml), installed into cluster and created ingress. Now I can get into websites.

**Comment by tirelibirefe** [comment]
Still have a similar problem:

![image](https://github.com/argoproj/argo-rollouts/assets/45227339/c217a358-2c25-411e-9f81-8fdb1cf030be)
and
![image](https://github.com/argoproj/argo-rollouts/assets/45227339/b1fb66f4-f03d-4e2a-a4a2-cb83332d3cb1)

...The address which is being listened is wrong. In my config ingress is enabled and  a different domain is set as ingress address.

**Comment by krzwiatrzyk** [comment]
Have the same problem as @tirelibirefe. 

Using Traefik IngressRoute to expose Argo Rollouts dashboard. I wonder, if this doesn't occur if namespace doesn't have any Argo Rollout CRs?
