### ISSUE TITLE
Operation cannot be fulfilled on rollouts.argoproj.io: the object has been modified

### ISSUE THREAD

**Issue by croomes** [argoproj/argo-rollouts#1904]
## Summary 

When creating a new rollout we sometimes see it get stuck and never progress.  Logs show it failing to update due to a resource conflict.  It retries but always get the same conflict error, even though it re-queues after each failure.

Related: #1775

My guess is that the revision update at: https://github.com/argoproj/argo-rollouts/blob/acf805423c48f0e037e6e5686e6d164465f33c51/rollout/sync.go#L92-L94 succeeds, and then causes the status update at: https://github.com/argoproj/argo-rollouts/blob/acf805423c48f0e037e6e5686e6d164465f33c51/rollout/sync.go#L104-L108 to get the conflict.  Both log the same error so it's hard to tell for sure.

I'm happy to work on a PR for this but I'm new to Argo and the code.  Normally I'd return after the revision update and do the status update on the next reconcile but it looks like the revision is incremented each time `syncReplicaSetRevision()` runs?  Alternatively, after the revision update, re-fetch the ReplicaSet to make sure we have the latest version for the status update.

Any thoughts or guidance appreciated!

## Diagnostics

What version of Argo Rollouts are you running?  v1.0.2

```
time="2022-03-09T17:57:31Z" level=info msg="Defaulting .spec.replica to 1" generation=1 namespace=testns resourceVersion=4389783140 rollout=app
time="2022-03-09T17:57:31Z" level=info msg="Started syncing rollout" generation=1 namespace=testns resourceVersion=4389783140 rollout=app
time="2022-03-09T17:57:35Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389783922 rollout=app
time="2022-03-09T17:57:35Z" level=info msg="Updating replica set 'app-746777884f' revision from 0 to 1" namespace=testns rollout=app
time="2022-03-09T17:57:35Z" level=info msg="Created ReplicaSet app-746777884f" namespace=testns rollout=app
time="2022-03-09T17:57:39Z" level=info msg="Created ReplicaSet app-746777884f (revision 1) with size 1" event_reason=NewReplicaSetCreated namespace=testns rollout=app
time="2022-03-09T17:57:39Z" level=info msg="Rollout updated to revision 1" event_reason=RolloutUpdated namespace=testns rollout=app
time="2022-03-09T17:57:44Z" level=info msg="rollout syncHandler queue retries: 7 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:57:44Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:57:44Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389783922 rollout=app time_ms=8391.492779
time="2022-03-09T17:57:44Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389783922 rollout=app
time="2022-03-09T17:57:44Z" level=info msg="persisted to informer" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:57:44Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:57:48Z" level=info msg="rollout syncHandler queue retries: 8 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:57:48Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:57:48Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4191.9283700000005
time="2022-03-09T17:57:48Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:57:48Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:57:48Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:57:52Z" level=info msg="rollout syncHandler queue retries: 9 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:57:52Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:57:52Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4200.384081
time="2022-03-09T17:57:52Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:57:52Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:57:52Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:57:57Z" level=info msg="rollout syncHandler queue retries: 10 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:57:57Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:57:57Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4599.406142999999
time="2022-03-09T17:57:57Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:57:57Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:57:57Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:01Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:01Z" level=info msg="rollout syncHandler queue retries: 11 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:58:01Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:01Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4598.759919
time="2022-03-09T17:58:01Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:01Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:05Z" level=info msg="rollout syncHandler queue retries: 13 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:58:05Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:05Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4205.47663
time="2022-03-09T17:58:05Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:05Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:05Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:10Z" level=info msg="rollout syncHandler queue retries: 14 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:58:10Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:10Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4194.796269
time="2022-03-09T17:58:10Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:10Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:10Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:14Z" level=info msg="rollout syncHandler queue retries: 15 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:58:14Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:14Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4200.356353
time="2022-03-09T17:58:14Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:14Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:18Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:22Z" level=info msg="rollout syncHandler queue retries: 16 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:58:22Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:22Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4408.043619
time="2022-03-09T17:58:22Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:22Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:32Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:37Z" level=info msg="rollout syncHandler queue retries: 17 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:58:37Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:37Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4398.639260000001
time="2022-03-09T17:58:37Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:37Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:47Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:51Z" level=info msg="rollout syncHandler queue retries: 18 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:58:51Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:58:51Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4200.2296719999995
time="2022-03-09T17:58:51Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:58:51Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:59:01Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:59:05Z" level=info msg="rollout syncHandler queue retries: 19 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:59:05Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:59:05Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4196.487878
time="2022-03-09T17:59:05Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:59:05Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:59:15Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:59:20Z" level=info msg="rollout syncHandler queue retries: 20 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:59:20Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:59:20Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4600.653727
time="2022-03-09T17:59:20Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:59:20Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:59:30Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:59:34Z" level=info msg="rollout syncHandler queue retries: 21 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:59:34Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:59:34Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4199.269765999999
time="2022-03-09T17:59:34Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:59:34Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:59:44Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:59:48Z" level=info msg="rollout syncHandler queue retries: 22 : key \"testns/app\"" namespace=testns rollout=app
time="2022-03-09T17:59:48Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:59:48Z" level=info msg="Reconciliation completed" generation=2 namespace=testns resourceVersion=4389784599 rollout=app time_ms=4198.823166
time="2022-03-09T17:59:48Z" level=error msg="roCtx.reconcile err Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
time="2022-03-09T17:59:48Z" level=error msg="Error: updating rollout revision" error="Operation cannot be fulfilled on rollouts.argoproj.io \"app\": the object has been modified; please apply your changes to the latest version and try again" namespace=testns rollout=app
time="2022-03-09T17:59:58Z" level=info msg="Started syncing rollout" generation=2 namespace=testns resourceVersion=4389784599 rollout=app
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by mcblair** [comment]
We're seeing this too, but consistently.

* Argo Rollouts installed with cluster scope to its own namespace
* Rollouts in `default` namespace properly scale down and cleanup old replicasets
* Rollouts in any other namespace does not scale down nor cleanup old replicasets
  * Furthermore, the pods in the old replicasets remain in the k8s `service` endpoint slices

**Comment by DanTulovsky** [comment]
We also see this occasionally.  Restarting argo-rollouts itself always fixes the problem.

**Comment by juanvasquezreyes** [comment]
is there any update on this?

**Comment by johnzheng1975** [comment]
is there any work around for this? like use version more than xx.xxx.xxx, or other ways to avoid this issue?
thanks.

**Comment by chris-altamimi** [comment]
Seeing the same issue on our end in AKS using Rollouts raw installation ( not helm chart ). Going to migrate to using the chart to see if it is resolved.

Restarting rollouts does not fix this for us

**Comment by zachaller** [comment]
Is anyone still seeing this on 1.3 and if you are are you running more than one rollouts controller in an HA setup?

**Comment by ianmuge** [comment]
We are still seeing this on 1.3.1

**Comment by zachaller** [comment]
And are you running multiple controllers? There was some pretty big issues with the way leader election that are fixed in master that might cause some of this?

**Comment by ianmuge** [comment]
yes, we are running a deployment with 2 replicas. What would you suggest?

**Comment by zachaller** [comment]
I would be curious if setting the replica count to one would help for now until 1.4 is released where I refactored the leader election code quite a bit. If that does not help we would need to look else where to what is modifing the rollout object

**Comment by ianmuge** [comment]
Sure thing, we can test that... It usually takes a couple of days for the error to show up. We shall check back in a week

**Comment by jstewart612** [comment]
> I would be curious if setting the replica count to one would help for now until 1.4 is released where I refactored the leader election code quite a bit. If that does not help we would need to look else where to what is modifing the rollout object

@zachaller sadly it didn't help us.  We've done releases since going replica count 1 and still see this all over the place.

**Comment by zachaller** [comment]
@jstewart612 Do you guys have any other controller in your cluster you could think of that would modify the rollout resource upon changes? Do you guys run rollouts in a cluster wide setup or a per namespace setup?

**Comment by zachaller** [comment]
@jstewart612 Also is it causing any issues like rollouts getting stuck or not progressing? I see this log a bit on our end as well so will spend some more time looking into it. A little bit of re queuing can be normal as long as it is not the rollouts controller causing the conflicting modifications. I know for services we do add an explicit re-queue on conflict when modifying services we might need to do the same for rollouts object and or find what is causing the conflict and fix that if it is within the controller.

**Comment by jstewart612** [comment]
@zachaller I did not yet dig into the object in question's modification history to determine what modified it.  Iirc that's going to be somewhat esoteric to track down, but I will dig into it.  I would suspect common things that may do this to be things like security solutions?  I can't think of much else aside from the Argo ecosystem that would touch the kinds of pods we were referencing.

**Comment by jstewart612** [comment]
@zachaller well turns out it's Lacework Admissions Controller and Argo Rollouts conflicting with each other.  I'll separately bug-ticket them.

**Comment by ianmuge** [comment]
@zachaller I can confirm that running it as a single replica worked for us, we shall update all our clusters to have the same. Your help is much appreciated and hope this shall be fixed in the next major version.

**Comment by zachaller** [comment]
thanks for the update @ianmuge

**Comment by zachaller** [comment]
@ianmuge this is now fixed in 1.4 there is an rc1 available if you want to test https://github.com/argoproj/argo-rollouts/releases/tag/v1.4.0-rc1

**Comment by ianmuge** [comment]
We shall try to test it on one of our envs, thanks
