### ISSUE TITLE
High CPU/Mem usage with Argo

### ISSUE THREAD

**Issue by MarkSRobinson** [argoproj/argo-rollouts#2443]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [x] I've inclued the version of argo rollouts.

**Describe the bug**

Often we get an argo pod with very high CPU and memory usage.  It happens often but it's not easy to trigger directly.

This is an argo instance before crashing, it didn't self recover.
![image](https://user-images.githubusercontent.com/2237823/204907183-49a3bd7f-5535-479a-8f9c-53ecebed6c6c.png)

This Argo instance OOM'd.  The other pods in the cluster don't consume as much memory.  After the crash, memory did not increase.
<img width="1632" alt="image" src="https://user-images.githubusercontent.com/2237823/204907247-2375c4e4-93c3-4ecc-a925-e3df4e742420.png">

**To Reproduce**

We deploy very often in a fairly large cluster and over time it appears that argo is leaking memory in some capacity.  The closest we can get to reproducing it is to let it run for a few hours/days.  This might be worth hooking up pprof or friends and dumping the perf data.  I've attached logs but I'm not sure how useful they would be.

**Expected behavior**

Argo shouldn't OOM/consume excessive CPU

**Screenshots**

**Version**

1.3.1

**Logs**
[log dump when we killed the pod](https://gist.github.com/MarkSRobinson/7a980d6304591581e90e1b31d22517c7)
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
I have a theory that this is due to a bug with leader election are you running your pods in an HA setup aka more than one rollouts controller pod? If so this should be fixed by this PR in master https://github.com/argoproj/argo-rollouts/pull/2291

**Comment by MarkSRobinson** [comment]
Would running in non-HA mode fix this issue?

**Comment by zachaller** [comment]
Yes, I would not recommend HA until we release 1.4

**Comment by zachaller** [comment]
I should also mention you could test with the `:latest` or `:master` image tag if you have some test cluster that you can test on. The issue I am pretty sure is the the controller pod that is not the master still has a bunch of informers that are watching for and adding rollout objects to it's informer cache however because the controller is not actually running they just build up forever causing high cpu and eventually an oom.

**Comment by MarkSRobinson** [comment]
Switching off the HA mode didn't fix the problem.  Here is a memory trace when running a single pod.  You can see it crashes at 12/02 20:00(ish).

<img width="877" alt="image" src="https://user-images.githubusercontent.com/2237823/205405235-3b424fab-e020-4b0d-88ad-b4e9b4974cb9.png">

Here is the CPU usage over the similar time frame
<img width="861" alt="image" src="https://user-images.githubusercontent.com/2237823/205405362-1399199b-05e3-4272-9d30-a32a6c005f61.png">

**Comment by zachaller** [comment]
I am not sure if that is actually a leak yet mainly because the CPU spikes seem to slightly correlate. Do you have any idea on what is going right at the 16:00 mark as in is there a lot of rollouts being modified or experiments or anlaysis runs etc. It also looks like you have about a 7GB limit set if that is what the orange line is. If so have you tried removing the limit to see if memory gets reduced after the spike?
