### ISSUE TITLE
blue-green stuck indefinitely during a scaling event with prePromotionAnalysis & previewReplicaCount

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#2931]
**Describe the bug**

Argo Rollouts v1.4.0

We have the following rollout:

```yaml
  strategy:
    blueGreen:
      activeService: guestbook-prod
      autoPromotionEnabled: true
      prePromotionAnalysis:
        templates:
        - templateName: guestbook-prod-synthetics
      previewReplicaCount: 1
      previewService: guestbook-prod-preview
      scaleDownDelayRevisionLimit: 3
      scaleDownDelaySeconds: 21600
```

The rollout was in the middle of a blue-green update. During the update, there was a scaling event. When we have a scaling event, we are supposed to reconcile replicaset replicas only, and nothing else.

However, during this event, I saw the following logs which displayed an incorrect patch:

```
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","Started syncing rollout"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","Syncing replicas only due to scaling event"
"2023-07-31T17:57:31Z",,,"Event(v1.ObjectReference{Kind:\""Rollout\"", Namespace:\""guestbook\"", Name:\""guestbook-prod\"", UID:\""11111111-2222-3333-4444-5555555555\"", APIVersion:\""argoproj.io/v1alpha1\"", ResourceVersion:\""1301676025\"", FieldPath:\""\""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down ReplicaSet guestbook-prod-945f86b8d (revision 1578) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","Scaled down ReplicaSet guestbook-prod-945f86b8d (revision 1578) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","Scaled down ReplicaSet guestbook-prod-7fcbb6cd57 (revision 1579) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","RS 'guestbook-prod-69d4fb6c74' has not reached the scaleDownTime"
"2023-07-31T17:57:31Z",,,"Event(v1.ObjectReference{Kind:\""Rollout\"", Namespace:\""guestbook\"", Name:\""guestbook-prod\"", UID:\""11111111-2222-3333-4444-5555555555\"", APIVersion:\""argoproj.io/v1alpha1\"", ResourceVersion:\""1301676025\"", FieldPath:\""\""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down ReplicaSet guestbook-prod-7fcbb6cd57 (revision 1579) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","Scaled down ReplicaSet guestbook-prod-69d4fb6c74 (revision 1577) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","RS 'guestbook-prod-7d86884d84' has not reached the scaleDownTime"
"2023-07-31T17:57:31Z",,,"Event(v1.ObjectReference{Kind:\""Rollout\"", Namespace:\""guestbook\"", Name:\""guestbook-prod\"", UID:\""11111111-2222-3333-4444-5555555555\"", APIVersion:\""argoproj.io/v1alpha1\"", ResourceVersion:\""1301676025\"", FieldPath:\""\""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down ReplicaSet guestbook-prod-69d4fb6c74 (revision 1577) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","Scaled down ReplicaSet guestbook-prod-7d86884d84 (revision 1576) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","RS 'guestbook-prod-6c6b8d9b9' has not reached the scaleDownTime"
"2023-07-31T17:57:31Z",,,"Event(v1.ObjectReference{Kind:\""Rollout\"", Namespace:\""guestbook\"", Name:\""guestbook-prod\"", UID:\""11111111-2222-3333-4444-5555555555\"", APIVersion:\""argoproj.io/v1alpha1\"", ResourceVersion:\""1301676025\"", FieldPath:\""\""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down ReplicaSet guestbook-prod-7d86884d84 (revision 1576) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","Scaled down ReplicaSet guestbook-prod-6c6b8d9b9 (revision 1575) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","Scaled down old RSes"
"2023-07-31T17:57:31Z",,,"Event(v1.ObjectReference{Kind:\""Rollout\"", Namespace:\""guestbook\"", Name:\""guestbook-prod\"", UID:\""11111111-2222-3333-4444-5555555555\"", APIVersion:\""argoproj.io/v1alpha1\"", ResourceVersion:\""1301676025\"", FieldPath:\""\""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down ReplicaSet guestbook-prod-6c6b8d9b9 (revision 1575) from 11 to 10"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","Timed out (false) [last progress check: 2023-07-31 17:56:20 +0000 UTC - now: 2023-07-31 17:57:31.18181953 +0000 UTC m=+140730.866096123]"
"2023-07-31T17:57:31Z","""guestbook-prod""","""guestbook""","msg=""Patched: {\""status\"":{\""blueGreen\"":{\""prePromotionAnalysisRunStatus\"":null},\""conditions\"":[{\""lastTransitionTime\"":\""2023-04-04T15:42:04Z\"",\""lastUpdateTime\"":\""2023-04-04T15:42:04Z\"",\""message\"":\""Rollout is paused\"",\""reason\"":\""RolloutPaused\"",\""status\"":\""False\"",\""type\"":\""Paused\""},{\""lastTransitionTime\"":\""2023-07-31T17:52:17Z\"",\""lastUpdateTime\"":\""2023-07-31T17:52:17Z\"",\""message\"":\""Rollout is not healthy\"",\""reason\"":\""RolloutHealthy\"",\""status\"":\""False\"",\""type\"":\""Healthy\""},{\""lastTransitionTime\"":\""2023-07-31T17:52:17Z\"",\""lastUpdateTime\"":\""2023-07-31T17:52:17Z\"",\""message\"":\""RolloutCompleted\"",\""reason\"":\""RolloutCompleted\"",\""status\"":\""False\"",\""type\"":\""Completed\""},{\""lastTransitionTime\"":\""2023-05-10T23:15:09Z\"",\""lastUpdateTime\"":\""2023-07-31T17:56:20Z\"",\""message\"":\""ReplicaSet \\\""guestbook-prod-7fcbb6cd57\\\"" is progressing.\"",\""reason\"":\""ReplicaSetUpdated\"",\""status\"":\""True\"",\""type\"":\""Progressing\""},{\""lastTransitionTime\"":\""2023-07-31T17:57:31Z\"",\""lastUpdateTime\"":\""2023-07-31T17:57:31Z\"",\""message\"":\""Rollout does not have minimum availability\"",\""reason\"":\""AvailableReason\"",\""status\"":\""False\"",\""type\"":\""Available\""}],\""observedGeneration\"":\""10120\""}}"" generation=10120 namespace=guestbook resourceVersion=1301676025 rollout=guestbook-prod"
```

Looking closer at the patch that the controller performed, you can see that `status.blueGreen.prePromotionAnalysisRunStatus` was nulled out (it previously had a Successful entry there)

```json
{
    "status": {
        "blueGreen": {
            "prePromotionAnalysisRunStatus": null     // <<<<<<<<< this should not have happened
        },
        "conditions": [
            {
                "lastTransitionTime": "2023-04-04T15:42:04Z",
                "lastUpdateTime": "2023-04-04T15:42:04Z",
                "message": "Rollout is paused",
                "reason": "RolloutPaused",
                "status": "False",
                "type": "Paused"
            },
            {
                "lastTransitionTime": "2023-07-31T17:52:17Z",
                "lastUpdateTime": "2023-07-31T17:52:17Z",
                "message": "Rollout is not healthy",
                "reason": "RolloutHealthy",
                "status": "False",
                "type": "Healthy"
            },
            {
                "lastTransitionTime": "2023-07-31T17:52:17Z",
                "lastUpdateTime": "2023-07-31T17:52:17Z",
                "message": "RolloutCompleted",
                "reason": "RolloutCompleted",
                "status": "False",
                "type": "Completed"
            },
            {
                "lastTransitionTime": "2023-05-10T23:15:09Z",
                "lastUpdateTime": "2023-07-31T17:56:20Z",
                "message": "ReplicaSet \\"guestbook-prod-7fcbb6cd57\\" is progressing.",
                "reason": "ReplicaSetUpdated",
                "status": "True",
                "type": "Progressing"
            },
            {
                "lastTransitionTime": "2023-07-31T17:57:31Z",
                "lastUpdateTime": "2023-07-31T17:57:31Z",
                "message": "Rollout does not have minimum availability",
                "reason": "AvailableReason",
                "status": "False",
                "type": "Available"
            }
        ],
        "observedGeneration": "10120"
    }
}
```

The fact that `status.blueGreen.prePromotionAnalysisRunStatus` was cleared, caused this issue. It resulted in the `reconcileActiveService()` method to never switch the active service to the desired ReplicaSet, even though the desired replicaset had reached full availability and prePromotionAnalysis had already passed (we just lost record of it). `completedPrePromotionAnalysis`() would return false:

```golang
// completedPrePromotionAnalysis checks if the Pre Promotion Analysis has completed successfully
func (c *rolloutContext) completedPrePromotionAnalysis() bool {
	if c.rollout.Spec.Strategy.BlueGreen == nil || c.rollout.Spec.Strategy.BlueGreen.PrePromotionAnalysis == nil {
		return true
	}
	currentAr := c.currentArs.BlueGreenPrePromotion
	if currentAr != nil && currentAr.Status.Phase == v1alpha1.AnalysisPhaseSuccessful {  
		return true   // <<<<<<<<<< we never get here
	}
	return false
}
```

**To Reproduce**

Induce a scaling event during a blueGreen rollout with prePromotionAnalysis and previewReplicaCount. The ideal time to do this is after prePromotionAnalysis had succeeded, and the controller is waiting for the desired replicaset to scale up from previewReplicaCount.

**Expected behavior**

**Screenshots**

**Version**

v1.4.0

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
The requirements for this bug:
* `prePromotionAnalysis`
* inopportune scaling event
* `previewReplicaCount`

A workaround to this might be to avoid using `previewReplicaCount`. The reason being that previewReplicaCount creates a window of opportunity where a scaling event could occur. When that happens, we would have lost our bookkeeping that prePromotionAnalysis was successful. So by avoid using `previewReplicaCount`, we would have reduced or eliminated this window where the scaling event could have happened.

**Comment by zachaller** [comment]
I would be curious about the reproducibility of this on master, this might possibly be fixed by: https://github.com/argoproj/argo-rollouts/pull/2689/files

**Comment by schlags** [comment]
> A workaround to this might be to avoid using previewReplicaCount. The reason being that previewReplicaCount creates a window of opportunity where a scaling event could occur. When that happens, we would have lost our bookkeeping that prePromotionAnalysis was successful. So by avoid using previewReplicaCount, we would have reduced or eliminated this window where the scaling event could have happened.

I don't think this window is eliminated, but might be reduced like you're saying. My case was the opposite - our HPA is very active on one application that uses a very similar selection of preAnalysis and BlueGreen. Adding the previewReplicaCount actually seemed to allow our analysisruns to complete successfully more often from the minimal testing I've been able to do.

To tack onto this, we are experiencing a similar bug; except the `Patch` will actually set Terminate to `true`, and cancel our analysisruns before completion. This unfortunately shows up in Argo as "Successful - Rollout Terminated" and continues with the deployment. Which is very undesirable, and feels dangerous.

**Comment by jessesuen** [comment]
Thanks for the additional datapoint. This tells me that in general, a scaling event might cause rollouts to lose some important status information (including terminate/analysis statuses). So the fix could be to make sure rollout controller does not touch  most status fields (at least fields it does not reconcile) during scaling events.

**Comment by RishabKumar** [comment]
I am experiencing the same, if application pod restarts then it causes the analysis run to terminate with successful status

**Comment by RishabKumar** [comment]
I am still facing this issue in Argo version 1.6.6
Can anyone here verify if it works ?

Steps to reproduce:
1. Spin up the application pod with a pre-analysis job.
2. While the pre analysis job is running, kill the application pod.
3. this will cause the analysis run to be marked as successfull and the rollout will also succeed, without starting up a new analysis run.
