### ISSUE TITLE
TrafficRoutingError with Traefik v3 (traefik.io/v1alpha1) on argo-rollouts v1.8.3

### ISSUE THREAD

**Issue by ayanhamza** [argoproj/argo-rollouts#4568]
Hi 👋

We are facing a TrafficRoutingError when using Argo Rollouts v1.8.3 with Traefik v3 CRDs (traefik.io/v1alpha1).

Although all required Traefik CRDs and resources exist and are valid, the rollout controller fails with:

TrafficRoutingError: the server could not find the requested resource

This looks like an incompatibility between argo-rollouts v1.8.3 and Traefik v3 API group (traefik.io).

**Environment**

Argo Rollouts version: v1.8.3 (stable)

Traefik CRDs: traefik.io/v1alpha1 (Traefik v3)

argoproj/argo-rollouts:v1.8.3

**Rollout spec (Traefik traffic routing)**
```
strategy:
  canary:
    stableService: interactions-cases-management-stable
    canaryService: interactions-cases-management-canary
    trafficRouting:
      traefik:
        weightedTraefikServiceName: interactions-cases-management
```

**Existing TraefikService (verified)**
```
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: interactions-cases-management
  namespace: digital-ns
spec:
  weighted:
    services:
      - name: interactions-cases-management-stable
        port: 8080
      - name: interactions-cases-management-canary
        port: 8080
```

**CRDs are present:**

traefikservices.traefik.io
ingressroutes.traefik.io

kubectl api-resources confirms availability.

**Logs from argo-rollouts controller**
```
time="2025-12-22T13:19:37Z" level=warning msg="the server could not find the requested resource" event_reason=TrafficRoutingError namespace=digital-ns rollout=interactions-cases-management
time="2025-12-22T13:19:37Z" level=error msg="rollout syncHandler error: the server could not find the requested resource"
```

**Expected behavior**

Argo Rollouts should be able to:

recognize TraefikService in traefik.io/v1alpha1

update weights in spec.weighted.services[]

proceed with canary steps without TrafficRoutingError

**Actual behavior**

Rollout reconciliation fails

Controller reports requested resource not found

Canary traffic routing never progresses

**Question**

Is Traefik v3 (traefik.io/v1alpha1) officially supported in argo-rollouts v1.8.3?
If not:

which version introduces proper support?

is there a compatibility matrix for Traefik major versions vs argo-rollouts?

**Comment by idurgakalyan** [comment]
https://github.com/argoproj/argo-rollouts/pull/4572, should resolve it.

**Comment by kostis-codefresh** [comment]
Traefik v3.x is also supported today (even with older Argo Rollout releases) via the Gateway API plugin https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/tree/main/examples/traefik

**Comment by mythilyjsq** [comment]
With which release, will https://github.com/argoproj/argo-rollouts/pull/4572 be included?

**Comment by dichico** [comment]
Hello! This is still not working in Argo Rollouts 1.9.0. Do you know when it's going to be updated?

**Comment by kostis-codefresh** [comment]
@dichico Do you get the same error or something different?

Can you attach to this issue a minimal example that shows the problem (Traefik service + rollout)

By the way I just tested yesterday Argo Rollout 1.9.0 and Traefik 3.7.0 via the Gateway API https://rollouts-plugin-trafficrouter-gatewayapi.readthedocs.io/en/latest/provider-status/ and it just works

**Comment by dichico** [comment]
Unfortunately my company doesn't use the Gateway API part.
I was able to fix this in 1.9.0 using extraArgs as shown in issue #3615 :
```
      args:
        - --traefik-api-group=traefik.io
        - --traefik-api-version=traefik.io/v1alpha1
```

My idea was that the new version of Rollouts would upgrade internally to this new api group and api version and not have require this extraArgs step.

**Comment by kostis-codefresh** [comment]
So it seems that the fix is not part of 1.9.0 because it was merged after the rc was cut. I assume it will be part of 1.10.0 though. So the workaround will not be needed any more
