### ISSUE TITLE
Failed job results in successful analysis run

### ISSUE THREAD

**Issue by nextrevision** [argoproj/argo-rollouts#521]
I'm using the Job metric provider for pre-promotion validation in a b/g scenario. The job results in failure (expected) but the analysis run still reports `Successful`. I expect the analysis run to also fail and cause the revision to be ineligible for promotion (automated or manual) unless otherwise ignored. If I set `autoPromotionEnabled` to `true` on my Rollout, the revision with the failed Job will be promoted automatically.

**Rollout Status**
```
$ kubectl argo rollouts -n example get rollout myapp
Name:            myapp
Namespace:       example
Status:          ॥ Paused
Strategy:        BlueGreen
Images:          registry.company.io/myapp:1.0.0 (active, preview)
Replicas:
  Desired:       1
  Current:       2
  Updated:       1
  Ready:         2
  Available:     1

NAME                                                       KIND         STATUS        AGE    INFO
⟳ myapp                                                    Rollout      ॥ Paused      41h
├──# revision:32
│  ├──⧉ myapp-64fc844b69                                   ReplicaSet   ✔ Healthy     113s   preview
│  │  └──□ myapp-64fc844b69-ptx8v                          Pod          ✔ Running     113s   ready:1/1
│  └──α myapp-64fc844b69-32                                AnalysisRun  ✔ Successful  48s    ✖ 1
│     └──⊞ e2f2718a-e8d4-4a7c-8867-7d8e17e6b01d.smoketest.1  Job          ✖ Failed      48s
├──# revision:31
│  ├──⧉ myapp-56c5c9749d                                   ReplicaSet   ✔ Healthy     4m35s  active
│  │  └──□ myapp-56c5c9749d-5qnjr                          Pod          ✔ Running     4m35s  ready:1/1
│  ├──α myapp-56c5c9749d-31.1                              AnalysisRun  ✔ Successful  3m36s  ✔ 1
│  │  └──⊞ 739b3158-dc61-4131-a09a-2b0f09a074a2.smoketest.1  Job          ✔ Successful  3m36s
```

```
$ kubectl -n example get pods
NAME                                                   READY   STATUS    RESTARTS   AGE
e2f2718a-e8d4-4a7c-8867-7d8e17e6b01d.smoketest.1-f4n9k   0/1     Error     0          2m20s
myapp-56c5c9749d-5qnjr                                 1/1     Running   0          6m7s
myapp-64fc844b69-ptx8v                                 1/1     Running   0          3m25s
```

```
$ kubectl -n example get jobs
NAME                                             COMPLETIONS   DURATION   AGE
e2f2718a-e8d4-4a7c-8867-7d8e17e6b01d.smoketest.1   0/1           2m29s      2m29s
```

```
$ kubectl -n example describe job e2f2718a-e8d4-4a7c-8867-7d8e17e6b01d.smoketest.1
Name:           e2f2718a-e8d4-4a7c-8867-7d8e17e6b01d.smoketest.1
Namespace:      example
Selector:       controller-uid=fc389554-01a1-4fee-84e8-76777e857e14
Labels:         analysisrun.argoproj.io/uid=e2f2718a-e8d4-4a7c-8867-7d8e17e6b01d
Annotations:    analysisrun.argoproj.io/metric-name: smoketest
                analysisrun.argoproj.io/name: myapp-64fc844b69-32
Controlled By:  AnalysisRun/myapp-64fc844b69-32
Parallelism:    1
Completions:    1
Start Time:     Thu, 28 May 2020 12:05:22 -0700
Pods Statuses:  0 Running / 0 Succeeded / 1 Failed
Pod Template:
  Labels:  controller-uid=fc389554-01a1-4fee-84e8-76777e857e14
           job-name=e2f2718a-e8d4-4a7c-8867-7d8e17e6b01d.smoketest.1
```

**Analysis Template**
```
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: smoketest
spec:
  args:
  - name: service-url
  metrics:
  - name: smoketest
    failureLimit: 1
    provider:
      job:
        spec:
          backoffLimit: 0
          template:
            spec:
              containers:
              - name: smoketest
                image: smoketest:image
                args:
                  - "{{ args.service-url }}"
```

**Rollout**
```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    rollout.argoproj.io/revision: "32"
  name: myapp
  namespace: example
  resourceVersion: "3948767"
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
  strategy:
    blueGreen:
      activeService: myapp
      autoPromotionEnabled: false
      prePromotionAnalysis:
        args:
        - name: service-url
          value: http://myapp-preview.example.svc.cluster.local:8080
        templates:
        - templateName: smoketest
      previewService: myapp-preview
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
        app.kubernetes.io/version: 1.0.0
    spec:
      containers: [...]
      restartPolicy: Always
      terminationGracePeriodSeconds: 160
```

**Comment by khewling** [comment]
We are seeing the same issue:
![image](https://user-images.githubusercontent.com/48773725/90826425-690e2680-e308-11ea-9266-78a406f8e7eb.png)

![image](https://user-images.githubusercontent.com/48773725/90826448-71fef800-e308-11ea-93e2-9669eecd3668.png)

**Comment by ruben-ojeda-mednax** [comment]
Please, fix this issue. The webmetric_test.go file only has scenarios where webServerStatus == 200, but we are getting 404 status code responses from the service and the deployment is considering it "Healthy".

**Comment by abatilo** [comment]
@jessesuen Any ideas when this will get worked on? This seems like kind of a non-starter for people that want automatic rollback on deployments

**Comment by abatilo** [comment]
If someone could give me a hint on where to start, I'd be willing to try and contribute!

**Comment by abatilo** [comment]
Following up here. It appears that setting `failureLimit` to 0 caused the rollout to cancel back. Someone had posted a similar question in the Argo Rollouts Slack and Jesse mentioned it. Maybe others here should try explicitly setting that value to 0?

**Comment by jessesuen** [comment]
There's been a lot of issues I've been working through with blue-green and analysis, in that it was basically broken. I feel like this issue may be covered by the v0.9.2 work in progress, as I have been focusing a lot on blue-green + analysis issues.

**Comment by jessesuen** [comment]
v0.9.2 is released with many fixes to blue-green in conjunction with analysis. I believe the issue is resolved but please reopen if still an issue.

**Comment by ruben-ojeda-mednax** [comment]
This is to confirm the issue was resolved:
![image](https://user-images.githubusercontent.com/48603217/96787593-03015680-13c0-11eb-8bb2-6eb8f605e95a.png)

**Comment by ahmetavc** [comment]
@jessesuen I am facing the same issue. My version is: Image: argoproj/argo-rollouts:v0.10.2
<img width="867" alt="Screen Shot 2021-01-18 at 12 10 28" src="https://user-images.githubusercontent.com/22712578/104895283-bb6e7480-5986-11eb-9f60-35e7e98d721d.png">

**Comment by keithmattix** [comment]
@jessesuen I'm seeing this happen with the release candidate `v1.0.0-rc1` with helm chart version `0.5.0`
<img width="996" alt="image" src="https://user-images.githubusercontent.com/1531662/117730855-b130ea00-b1b2-11eb-982c-af7aa676fe29.png">
.

**Comment by Sanchit-20** [comment]
Still see the issue with the latest version `v1.0.2` @jessesuen 
<img width="1274" alt="Screenshot 2021-07-20 at 4 20 00 PM" src="https://user-images.githubusercontent.com/22833885/126311999-83d530b0-7f98-4ae5-97cb-558cd0465547.png">

**Comment by ixxeL2097** [comment]
Same issue with release candidate `1.2.0-rc2` , does someone have any hint on this problem ?

**Comment by ruben-ojeda-mednax** [comment]
We haven't seen this issue again. A failed rollout always goes into a "Degraded" status if it fails the AnalysisRun. We are also running the same version.

**Comment by ixxeL2097** [comment]
Ok I see. I am currently investigating on this. I am most likely doing something wrong, but my job fails and `AnalysisRun` stay healthy instead of degrading my rollout. Maybe something to do with my istio sidecar injection container I guess.

**Comment by ruben-ojeda-mednax** [comment]
No worries, if AnalysisRun STATUS was "Error", then the rollout STATUS should be "Degraded", but if it was "Successful", I would recommend you look for something else down stream.

**Comment by ixxeL2097** [comment]
I tried to disable Istio sidecar injection and still same behaviour :

![image](https://user-images.githubusercontent.com/19793672/156848934-a726aa58-7175-45aa-8594-6bbe73f5eda5.png)

The `AnalysisRun` status is successful and I don't understand why actually 

![image](https://user-images.githubusercontent.com/19793672/156849027-b70c7a7d-9a94-473a-8764-e32afda52f93.png)

**Comment by ruben-ojeda-mednax** [comment]
Your pictures show jobs failing. Is your AnalysisTemplate provider a job? From here: https://argoproj.github.io/argo-rollouts/analysis/job/? I would double check the job command exit code too, just in case.

**Comment by ixxeL2097** [comment]
Indeed my `AnalysisTemplate` provider is a job. I will double check the exit code first

**Comment by ixxeL2097** [comment]
ok, I figured it out. Seemed like I used a wrong image to execute my job. I was using `curlimages/curl:latest` at first and then replacing that image with a different one from my personal library worked. Anyway, thanks a lot for your help dude !

**Comment by marzlarz** [comment]
We are still seeing this same issue on v1.8.1, opened new bug: #4393
